#!/bin/bash
###############################################################################
# This script is to tune the ACOTSP software.
#
# PARAMETERS:
# $1 is the ID of the candidate to be evaluated
# $2 is the c2 ID
# $3 is the c1
# $4 is the c2 name
# The rest ($* after `shift 4') are parameters for running ACOTSP
#
# RETURN VALUE:
# This script should print a single numerical value (the value to be minimized).
###############################################################################
python call_201.py --nfe 4e+3 --n $5 --w_1 $6 --c1_1 $7 --c2_1 $8 --k $9 --beta ${10} --w_2 ${11} --c1_2 ${12} --c2_2 ${13} --bbob "function_indices:1,15 dimensions:10 instance_indices:1-10"

exit 0
