#!/bin/bash
###############################################################################
# This script is to tune the ACOTSP software.
#
# PARAMETERS:
# $1 is the ID of the candidate to be evaluated
# $2 is the c2 ID
# $3 is the c1
# $4 is the c2 name
# The rest ($* after `shift 4') are parameters for running ACOTSP
#
# RETURN VALUE:
# This script should print a single numerical value (the value to be minimized).
###############################################################################
EXE=~python ./call_ga.py

$EXE " --nfe 1e+5 " --n "$5" --k "$6" --alpha "$7" --pr "$8" " --bbob function_indices:1,15 dimensions:10 instance_indices:1-10"

exit 0
